qc:
  _DEFAULT_:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  LBEmel:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25

persample_reads:
  samplesets:
    - EucPan

sample_sets: []

mapping:
  aligners:
    - bwa
  refs:
    - grandisv2chl
  samplesets:
    - DP15_highcov
    - RymerMarri
  ngm:
    sensitivity: 0.5

refs:
  grandis: /g/data/xe2/references/eucalyptus/grandis/Egrandis_v2.fasta
  grandisv2chl: /g/data/xe2/references/eucalyptus/grandis_v2_chloro/Egrandis-v2-plus-chloro.fasta
  emel-scott: /g/data/xe2/references/eucalyptus/emel_scott/Emelliodora_CSIROg1_SISH00000000.1.fasta
  E_albens: /g/data/xe2/references/eucalyptus/scott-final-2020/E_albens2.fasta
  E_grandis: /g/data/xe2/references/eucalyptus/scott-final-2020/E_grandis.fasta
  E_melliodora: /g/data/xe2/references/eucalyptus/scott-final-2020/E_mell_canu_dip.fasta
  E_sideroxylon: /g/data/xe2/references/eucalyptus/scott-final-2020/E_sideroxylon2.fasta
  C_calophylla: /g/data/xe2/references/eucalyptus/scott-final-2020/C_calophylla.fasta
#A_floribunda: /g/data/xe2/references/eucalyptus/scott-final-2020/A_floribunda.fasta
#C_maculata: /g/data/xe2/references/eucalyptus/scott-final-2020/C_maculata.fasta
#E_caleyi: /g/data/xe2/references/eucalyptus/scott-final-2020/E_caleyi.fasta
#E_camaldulensis: /g/data/xe2/references/eucalyptus/scott-final-2020/E_camaldulensis.fasta
#E_cloeziana: /g/data/xe2/references/eucalyptus/scott-final-2020/E_cloeziana.fasta
#E_coolabah: /g/data/xe2/references/eucalyptus/scott-final-2020/E_coolabah.fasta
#E_globulus: /g/data/xe2/references/eucalyptus/scott-final-2020/E_globulus.fasta
#E_polyanthemos: /g/data/xe2/references/eucalyptus/scott-final-2020/E_polyanthemos.fasta


denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  sourmash_sketchsize: 1e5
  ksize: 21
  kwip_sets: []
  mash_sets: # we can subset from everything for (sour)mash
    - all_samples
  sourmash_sets: []

varcall:
  minmapq:
    bwa: 30
    ngm: 10
  minbq: 15
  chunksize:
    mpileup:  10000000
    freebayes:   50000
    gatk-hc:   3000000
  samplesets:
    HMBEmel:
      theta_prior: 0.1
      aligners:
        - bwa
      callers:
        - mpileup
          #- freebayes
      refs:
        - grandisv2chl
    AdnatariaHighCoverage:
      theta_prior: 0.1
      aligners:
        - bwa
      callers:
        - mpileup
          #- freebayes
      refs:
        - grandisv2chl
    DP15_highcov:
      aligners:
        - bwa
      callers:
        - mpileup
          #- freebayes
      refs:
        - grandisv2chl
    RymerMarri:
      theta_prior: 0.05
      aligners:
        - bwa
      callers:
        #- freebayes
        - mpileup
      refs:
        - grandisv2chl
        - C_calophylla
    SPP_E_melliodora: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_melliodora"]}
    SPP_C_calophylla: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "C_calophylla"]}
    SPP_E_albens: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_albens"]}
    SPP_E_grandis: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_grandis"]}
    SPP_E_melliodora: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_melliodora"]}
    SPP_E_sideroxylon: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_sideroxylon"]}
    #SPP_A_floribunda: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "A_floribunda"]}
    #SPP_C_maculata: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "C_maculata"]}
    #SPP_E_caleyi: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_caleyi"]}
    #SPP_E_camaldulensis: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_camaldulensis"]}
    #SPP_E_cloeziana: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_cloeziana"]}
    #SPP_E_coolabah: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_coolabah"]}
    #SPP_E_globulus: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_globulus"]}
    #SPP_E_polyanthemos: {"theta_prior": 0.1, "aligners": ["bwa"], "callers": ["mpileup"], "refs": ["grandisv2chl", "E_polyanthemos"]}
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above is presence rate, >20%

angsd:
  aligners:
    - bwa
  refs:
    - grandisv2chl
  samplesets:
    - DP15_loc01_alb
    - DP15_loc03_alb
    - DP15_loc05_alb
    - DP15_loc05_sid
    - DP15_loc06_alb
    - DP15_loc07_alb
    - DP15_loc08_alb
    - DP15_loc08_sid
    - DP15_loc09_alb
    - DP15_loc09_sid
    - DP15_loc10_sid
    - DP15_loc11_alb
    - DP15_loc11_sid
    - DP15_loc12_sid
    - DP15_loc13_alb
    - DP15_loc14_alb
    - DP15_loc15_alb
    - DP15_loc16_alb
    - DP15_loc17_sid
    - DP15_loc18_alb
    - DP15_loc19_alb
    - DP15_loc20_alb
    - DP15_loc21_alb
    - DP15_loc22_alb
    - DP15_loc23_sid
    - DP15_loc24_alb
    - DP15_loc24_sid
    - DP15_loc25_alb
    - DP15_loc26_alb
    - DP15_loc27_sid
    - DP15_loc28_sid
    - DP15_loc29_alb
    - DP15_loc30_sid
    - DP15_loc31_sid
    - DP15_loc32_alb
    - DP15_loc33_alb
    - DP15_loc34_alb
    - DP15_loc35_sid
    - DP15_loc36_sid
    - DP15_loc37_sid
    - DP15_loc38_sid
    - DP15_loc39_alb
  chroms:
    - Chr01
    - Chr02
    - Chr03
    - Chr04
    - Chr05
    - Chr06
    - Chr07
    - Chr08
    - Chr09
    - Chr10
    - Chr11

  # angsd:
  #   chunksize: 1000000
  #   filters:
  #     angsd_default:  "-SNP_pval 1e-3  -minMaf 0.0001 -minInd 10 -setMinDepth 10 -minQ 10"
  #     perloc_default:  "-SNP_pval 1e-3  -minMaf 0.0001 -setMinDepth 3 -minQ 10"
  #   aligners:
  #     - bwa
  #   refs:
  #     - grandisv2chl
  #   samplesets:
  #     - Project2-sideroxylon-no-outlier
  #   locationsets:
  #     - loc01_alb
  # 
  # pcangsd:
  #   angsd_chunksize: 100000
  #   aligners:
  #     - bwa
  #   refs:
  #     - grandisv2chl
  #   samplesets:
  #     - Project2-albens-no-outlier
  #   nsnps:
  #     - 100000
  #   reps: 20
  #   angsd_filters: "-SNP_pval 1e-4 -doMaf 2 -doPost 1  -minMaf 0.01 -minInd 50"
  #   admix:
  #     K: [1,2,3,4,5,6]
  #     alpha: ["0.0", 0.001, 0.01, 0.1, 0.2]
  #     seeds: [1, 2, 3, 5, 7]
